db.url=jdbc:postgresql://db:5432/LibreriaDB
db.user=postgres
db.password=juan1234
db.maxPoolSize=10
db.minIdle=2
db.connectionTimeout=30000

jwt.secret=claveSecretaSuperLargaParaFirmarJwtHS256EnLaLibreriaVirtual

cors.allowedOrigins=http://localhost:3000
